name: gke-plugin
version: 1.0
rundeckPluginVersion: 1.2
author: Diego Maia
date: Tue Jan 2021
providers:
  - name: gke
    service: WorkflowNodeStep
    title: 'GKE Scripting'
    description: 'This gke executor complies with the GKE architecture, mandatory service accounts must be used for full execution.'
    plugin-type: script
    script-interpreter: python -u
    script-file: main
    script-args: ${config.source} ${config.destination}
    config:
      - name: gke_command
        type: String
        title: "Commands"
        description: "Build a bash script and use the tools, gcloud, helm and kubectl"
        default: |
            #!/bin/bash
        required: true
        renderingOptions:
          displayType: CODE
          codeSyntaxMode: sh
      - type: String
        name: gcp_project_name
        title: Project Name
        required: true
        description: 'GCP Project Name'
        renderingOptions:
          grouping: secondary
          groupName: Connection   
      - type: String
        name: gcp_project_region
        title: Project Region
        required: true
        description: 'GCP Project Region'
        renderingOptions:
          grouping: secondary
          groupName: Connection   
      - type: String
        name: gcp_gke_cluster_name
        title: Cluster Name
        required: true
        description: 'GKE Cluster Name'
        renderingOptions:
          grouping: secondary
          groupName: Connection   
      - type: String
        name: gcp_service_account_name
        title: Service Account Name
        required: true
        description: 'Service Account Name'
        renderingOptions:
          grouping: secondary
          groupName: Connection   
      - type: String
        name: gcp_service_account
        title: Service Account
        required: true
        description: 'Service Account Key'
        renderingOptions:
          grouping: secondary
          groupName: Connection
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
 