#!/usr/bin/env python
# git-push

# required 
# pip install gitpython==2.1.15

import os,sys
from git import Git,Repo
from shutil import rmtree

GIT_URL = os.getenv("RD_CONFIG_GIT_URL")
GIT_REPO_LOCAL_DIR = os.getenv("RD_CONFIG_GIT_REPO_LOCAL_DIR")
GIT_SSH_KEY = os.getenv("RD_CONFIG_GIT_SSH_KEY")
GIT_COMMIT_MESSAGE = os.getenv("RD_CONFIG_GIT_COMMIT_MESSAGE")

def main():
    try:
        git_ssh_identity_file = os.path.expanduser(GIT_SSH_KEY).replace('\r\n', os.linesep)
        f = open("/tmp/.tmp_k", "w")
        f.write(git_ssh_identity_file+'\n')
        f.close()
        os.chmod("/tmp/.tmp_k", 0o400)

        git_ssh_cmd = 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/.tmp_k' 
        repo = Repo(GIT_REPO_LOCAL_DIR)
        repo.git.add(update=True)
        repo.index.commit(GIT_COMMIT_MESSAGE)
        origin = repo.remote(name='origin')
        origin.push(env=dict(GIT_SSH_COMMAND=git_ssh_cmd))

        print('Push process complete ')
        print('Commit message: '+GIT_COMMIT_MESSAGE)
        print('Git URL: '+GIT_URL)

    except OSError as e:
        print >>sys.stderr, "Error:", e
        sys.exit(1)

    finally:
        os.remove('/tmp/.tmp_k')

if __name__ == '__main__':
    main()